### ISSUE TITLE
Is it possible to use a different Ruby namespace?

### ISSUE THREAD

**Issue by danielsdeleo** [Nordstrom/chef-dk-template-plugin#1]
First of all, this is super cool, thanks for writing and sharing.

I'm wondering if it's possible for this project to not share the `ChefDK` ruby namespace. I looked through the code a bit and didn't find a technical reason why you had to use `ChefDK`, though I may be overlooking something obvious or it could be a result of some library you're using. In any case, when you use, e.g., `ChefDK::Template`, this prevents ChefDK from having its own class or module with this name, which can lead to nasty issues for end users if we accidentally stomp on each other.

If there is some technical reason why you have to use `ChefDK`, but I could perhaps help make changes to ChefDK to make it possible for you to use a different namespace, please feel free to ask.

Thanks again for publishing this project, I know a ton of folks will find this very helpful.

**Comment by jf647** [comment]
No, there's no reason it has to be in ChefDK - I figured it could go either way - either getting adapted and brought in as part of ChefDK or taking on a life of its own.  And I can blow it up in any way I want as long as the major is 0.

I'll change it with 0.2 and yank the 0.1 gems from rubygems once the new one is up. 

Now, to find a cute name that somehow encompasses food, composition and sharing.  I wonder if "Instagram" is taken? :P

**Comment by danielsdeleo** [comment]
Good luck finding a food-related name that isn't already taken :wink: I don't think you'll really need to yank the old one, but I'll leave that to you. Thanks!

**Comment by jf647** [comment]
Done: https://github.com/Nordstrom/chef-gen-flavors

**Comment by danielsdeleo** [comment]
Thanks again, I think this is a case where good fences make good neighbors :smile: 

Don't hesitate to ask if there's anything we can do in ChefDK to help you be successful.
